<?php

/**
 * wallee Magento
 *
 * This Magento extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var Wallee_Payment_Block_Payment_Form $block */
$block = $this;

/* @var Wallee_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

/* @var Wallee_Payment_Helper_Data $helper */
$helper = $block->helper('wallee_payment');

$code = $block->getMethodCode();
$tokens = $block->getTokens();
$selectedToken = $this->getInfoData('wallee_token');
?>

<ul id="payment_form_<?php echo $code ?>" style="display:none">
	<li>
		<?php echo $helper->__('A charge flow will be used to process the payment.') ?>
	</li>
	<?php if (!empty($tokens)) : ?>
    	<li>
    		<div><?php echo $helper->__('The customer can be charged by using an existing token. If left empty, no token is used.') ?></div>
    		<div class="input-box">
    			<label for="<?php echo $method->getCode() ?>_token"><?php echo $helper->__('Token:') ?></label>
        		<select id="<?php echo $method->getCode() ?>_token" name="payment[wallee_token]">
        			<option value=""></option>
        			<?php foreach ($tokens as $token) : ?>
        				<option value="<?php echo $token->getId() ?>" <?php echo $selectedToken == $token->getId() ? 'selected="selected"' : '' ?>><?php echo $token->getName() ?> (<?php echo $helper->translate($token->getConnector()->getName()) ?>)</option>
        			<?php endforeach; ?>
        		</select>
        	</div>
    	</li>
	<?php endif; ?>
</ul>