<?php

/**
 * Wallee Magento
 *
 * This Magento extension enables to process payments with Wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var Wallee_Payment_Block_Adminhtml_Notification $block */
$block = $this;

/* @var Wallee_Payment_Helper_Data $helper */
$helper = $block->helper('wallee_payment');

$numberOfManualTasks = $block->getNumberOfManualTasks();
$totalNumberOfManualTasks = array_sum($numberOfManualTasks);
?>

<?php if ($block->isAdminNotificationEnabled() && $totalNumberOfManualTasks > 0) : ?>
	<div class="notification-global notification-global-notice">
		<span class="f-right">
    		<?php if (count($numberOfManualTasks) == 1) : ?>
    			<a href="<?php echo $block->getManualTasksUrl(key($numberOfManualTasks)) ?>" target="_blank"><?php echo $helper->__('View in wallee') ?></a>
    		<?php else : ?>
    			<a href="<?php echo $block->getManualTasksUrl() ?>" target="_blank"><?php echo $helper->__('View in wallee') ?></a>
    		<?php endif; ?>
		</span>
		<strong><?php echo $helper->__('wallee:') ?></strong>
		<?php if ($totalNumberOfManualTasks == 1) : ?>
		    <?php echo $helper->__('There is a manual task that needs your attention.') ?>
		<?php else : ?>
			<?php echo $helper->__('There are %s manual tasks that need your attention.', $totalNumberOfManualTasks) ?>
		<?php endif; ?>
	</div>
<?php endif; ?>