<?php

/**
 * Wallee Magento
 *
 * This Magento extension enables to process payments with Wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var Wallee_Payment_Block_Payment_Checkout $block */
$block = $this;

$javaScriptUrl = $block->getJavaScriptUrl();
?>

<?php if ($javaScriptUrl) : ?>
    <script type="text/javascript" src="<?php echo $javaScriptUrl ?>"></script>
<?php endif; ?>