<?php

/**
 * wallee Magento 1
 *
 * This Magento extension enables to process payments with wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var Wallee_Payment_Block_Payment_Form $block */
$block = $this;

/* @var Wallee_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

$code = $block->getMethodCode();
$imageUrl = $block->getImageUrl();
?>

<ul class="form-list" id="payment_form_<?php echo $code ?>" style="display:none">
	<?php if ($method->getConfigData('show_description') || ($method->getConfigData('show_image') && $imageUrl != null)) : ?>
		<li>
    		<table style="width: 100%;">
    			<tr>
    				<td>
    					<?php if ($method->getConfigData('show_description')) : ?>
    						<?php echo $method->getConfigData('description') ?>
    					<?php endif; ?>
    				</td>
    				<td>
    					<?php if ($method->getConfigData('show_image') && $imageUrl != null) : ?>
    						<img src="<?php echo $imageUrl ?>" width="50" style="float: right;" />
    					<?php endif; ?>
    				</td>
    			</tr>
    		</table>
    	</li>
    <?php endif; ?>
	<li>
		<div id="wallee_payment_method_form_<?php echo $method->getPaymentMethodConfigurationId() ?>"></div>
		<script type="text/javascript">
			MageWallee.Checkout.registerMethod('<?php echo $code ?>', <?php echo $method->getPaymentMethodConfiguration()->getConfigurationId() ?>, 'wallee_payment_method_form_<?php echo $method->getPaymentMethodConfigurationId() ?>');
		</script>
	</li>
	<li>
		<div id="wallee_payment_method_form_<?php echo $method->getPaymentMethodConfigurationId() ?>_errors"></div>
	</li>
</ul>