<?php

/**
 * Wallee Magento
 *
 * This Magento extension enables to process payments with Wallee (https://wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 * @link https://github.com/wallee-payment/magento
 */

/* @var Wallee_Payment_Block_Payment_Info $block */
$block = $this;

/* @var Wallee_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

/* @var Wallee_Payment_Helper_Data $helper */
$helper = $block->helper('wallee_payment');

$imageUrl = $block->getImageUrl();
?>

<div><?php echo $method->getTitle() ?></div>
<?php if ($method->getConfigData('show_image') && $imageUrl != null) : ?>
	<img src="<?php echo $imageUrl ?>" width="50" style="margin-top: 10px;" />
<?php endif; ?>

<?php if ($block->isCustomerDownloadInvoiceAllowed() || $block->isCustomerDownloadPackingSlipAllowed()) : ?>
	<div style="margin-top: 20px;">
        <?php $invoiceDownloadUrl = $block->getDownloadInvoiceUrl(); ?>
		<?php if ($block->isCustomerDownloadInvoiceAllowed() && $invoiceDownloadUrl) : ?>
        		<a href="<?php echo $invoiceDownloadUrl?>"><?php echo $helper->__('Download Invoice') ?></a><br/>
        <?php endif; ?>

        <?php $packingSlipDownloadUrl = $block->getDownloadPackingSlipUrl(); ?>
		<?php if ($block->isCustomerDownloadPackingSlipAllowed() && $packingSlipDownloadUrl) : ?>
        		<a href="<?php echo $packingSlipDownloadUrl?>"><?php echo $helper->__('Download Packing Slip') ?></a><br/>
        <?php endif; ?>
	</div>
<?php endif; ?>