<?php

/**
 * Wallee Magento
 *
 * This Magento extension enables to process payments with Wallee (https://www.wallee.com/).
 *
 * @package Wallee_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var Wallee_Payment_Block_Adminhtml_Sales_Order_View $block */
$block = $this;
?>
<?php if ($block->hasPendingRefund()) : ?>
	<div id="messages">
		<ul class="messages">
			<li class="notice-msg">
				<ul>
					<li>
						<span>
							<?php echo $block->helper('wallee_payment')->__('This order has a pending refund request.') ?>
						</span>
						<span class="f-right">
							<a href="<?php echo $block->getRefundUrl() ?>"><?php echo $block->helper('wallee_payment')->__('Send Refund Request') ?></a>
						</span>
					</li>
				</ul>
			</li>
		</ul>
	</div>
<?php endif; ?>